version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: "Installer Docker"
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo service docker start
