name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: nettoyage docker
      run: |
        docker system prune -a -f

    - name: Build et push de l’image Docker
      run: |
        # Utilisation du NodePort externe (30470)
        IMAGE_NAME="$(minikube ip):30470/project-python"
    
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:v1
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:v1

    - name: deploy
      run: |
        docker pull $(minikube ip):30470/project-python
        minikube image load $(minikube ip):30470/project-python:latest
        kubectl delete deployment project2-pipeline --ignore-not-found=true
        kubectl create deployment project2-pipeline --image=$(minikube ip):30470/project-python:latest -o yaml > deploy-project2-pipeline.yaml
        kubectl apply -f deploy-project2-pipeline.yaml
        kubectl expose deployment/project2-pipeline --type="NodePort" --port=5000 --name=project2-pipeline
        kubectl get pods
        kubectl get svc
        kubectl get ingress

      

