name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build et tag de l'image
      run: |
        docker build -t ton-image:latest .
        docker tag ton-image:latest ton-image:v1

    - name: Pousser l'image dans le registry
      run: |
        docker push ton-image:latest
        docker push ton-image:v1


  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: SSH into VM and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        script: |
          docker pull http://$(minikube ip):30470/my-image-name:latest
          docker stop mon-conteneur || true
          docker rm mon-conteneur || true
          docker run -d --name mon-conteneur -p 8081:80 http://$(minikube ip):30470/my-image-name:latest
