name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build et push de l’image Docker
      run: |
        # Utilisation du NodePort externe (30470)
        IMAGE_NAME="$(minikube ip):30470/ton-image"
    
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:v1
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:v1

    - name: deploy
      run: |
        docker pull $IMAGE_NAME
        minikube image load $IMAGE_NAME:latest
        kubectl create deployment project --image=$IMAGE_NAME:latest --dry-run=client -o yaml > deploy-project.yaml
        kubectl apply -f deploy-project.yaml

