name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
   
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build et push de l’image Docker
      run: |
        # Utilisation du NodePort externe (30470)
        IMAGE_NAME="$(minikube ip):30470/ton-image"
    
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:v1
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:v1


          docker stop mon-conteneur || true
          docker rm mon-conteneur || true
          docker run -d --name mon-conteneur -p 8081:80 $(minikube ip):30470/my-image-name:latest
