name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: nettoyage docker
      run: |
        docker system prune -a -f

    - name: Build et push de l’image Docker
      run: |
        # Utilisation du NodePort externe (30470)
        IMAGE_NAME="$(minikube ip):30470/project-python"
    
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:v1
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:v1

    - name: deploy
      run: |
        # Récupérer l'adresse IP de Minikube
        MINIKUBE_IP=$(minikube ip)
    
        # Pull l'image Docker
        docker pull $MINIKUBE_IP:30470/project-python:latest
    
        # Charger l'image dans Minikube
        minikube image load $MINIKUBE_IP:30470/project-python:latest
    
        # Supprimer l'ancien déploiement s'il existe
        kubectl delete deployment project2-pipeline --ignore-not-found=true
    
        # Supprimer l'ancien service pour éviter l'erreur AlreadyExists
        kubectl delete svc project2-pipeline --ignore-not-found=true
    
        # Déployer l'application
        cat <<EOF | kubectl apply -f -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: project2-pipeline
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: project2-pipeline
          template:
            metadata:
              labels:
                app: project2-pipeline
            spec:
              containers:
                - name: project-python
                  image: $MINIKUBE_IP:30470/project-python:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 5000
        EOF
    
        # Ajouter un délai pour s'assurer que le pod démarre correctement
        sleep 5
    
        # Exposer l'application en NodePort
        kubectl expose deployment/project2-pipeline --type="NodePort" --port=5000 --name=project2-pipeline
    
        # Vérifier que tout fonctionne
        kubectl get pods
        kubectl get svc
        kubectl get ingress



      

