name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build et push de l’image Docker
      run: |
        REGISTRY="10.102.213.145:31713"
        IMAGE_NAME="$REGISTRY/ton-image"
    
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:v1
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:v1


  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: SSH into VM and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        script: |
          docker pull http://$(minikube ip):31713/my-image-name:latest
          docker stop mon-conteneur || true
          docker rm mon-conteneur || true
          docker run -d --name mon-conteneur -p 8081:80 http://$(minikube ip):31713/my-image-name:latest
